// <auto-generated />
using DevResourceAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevResourceAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260109133616_UpdateUserTableForBCrypt")]
    partial class UpdateUserTableForBCrypt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevResourceAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Backend Geliştirme",
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Frontend Geliştirme",
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Siber Güvenlik",
                            UserId = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Veritabanı Sistemleri",
                            UserId = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Yapay Zeka ve Veri Bilimi",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("DevResourceAPI.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Kapsamlı .NET ve C# rehberi.",
                            Title = "Microsoft .NET Documentation",
                            Url = "https://learn.microsoft.com/dotnet/",
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Modern Frontend geliştirme kılavuzu.",
                            Title = "React Official Docs",
                            Url = "https://react.dev/",
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Web uygulama güvenliği için en kritik 10 risk listesi.",
                            Title = "OWASP Top Ten",
                            Url = "https://owasp.org/www-project-top-ten/",
                            UserId = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "İleri seviye SQL ve DB yönetimi dersleri.",
                            Title = "PostgreSQL Tutorial",
                            Url = "https://www.postgresqltutorial.com/",
                            UserId = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "Yapay zeka modelleri için açık kaynaklı kütüphane.",
                            Title = "TensorFlow Hub",
                            Url = "https://www.tensorflow.org/",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("DevResourceAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DevResourceAPI.Models.Category", b =>
                {
                    b.HasOne("DevResourceAPI.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevResourceAPI.Models.Resource", b =>
                {
                    b.HasOne("DevResourceAPI.Models.Category", "Category")
                        .WithMany("Resources")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevResourceAPI.Models.User", "User")
                        .WithMany("Resources")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevResourceAPI.Models.Category", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("DevResourceAPI.Models.User", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
